# .github/workflows/scrape-slopes.yml
name: Scrape Phoenix Park Slopes

on:
  schedule:
    - cron: '30 22 * * *'  # UTC 22:30 = KST 07:30
  workflow_dispatch:        # 수동 실행 가능

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create package.json
        run: |
          echo '{
            "name": "slope-scraper",
            "type": "module",
            "dependencies": {
              "axios": "^0.27.2",
              "cheerio": "^1.0.0-rc.12",
              "firebase-admin": "^11.0.0"
            }
          }' > package.json

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scraper.js
